with-expecter: true
dir: "mocks/{{.PackagePath}}"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/backtesting-org/kronos-cli/pkg:
    config:
      recursive: true
      all: true
